project_id = "davjlszmguixtuavtrxh"

[functions.system-health]
verify_jwt = false

[functions.student-signup]
verify_jwt = false

[functions.teacher-signup]
verify_jwt = false

[functions.parent-signup]
verify_jwt = false